# Stage 1 - the build process
FROM node:14.17.4 as build-deps
WORKDIR /usr
COPY package.json ./
RUN yarn
COPY . ./
RUN yarn build

# Stage 2 - the production environment

FROM nginx:1.12-alpine
COPY --from=build-deps /usr/build /usr/share/nginx/html
EXPOSE 80

ENTRYPOINT cd /usr/share/nginx/html/ && envsubst < config.js > temp.js && mv temp.js config.js && nginx -g 'daemon off;'